site_name: Tez
site_description: 'Tez: a simple pytorch trainer'
site_url: https://abhi1thakur.github.io/tez/


# Repo
repo_url: https://github.com/abhi1thakur/tez 
repo_name: abhi1thakur/tez
edit_uri: ''

# Copyright
copyright: Copyright &copy; 2021
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - search.share
    # nav bar top
    - navigation.tabs
    - navigation.sections
    - navigation.top

  icon:
    repo: fontawesome/brands/github-square
  palette:
  - scheme: default
    primary: cyan
    accent: deep orange
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  - scheme: slate
    primary: blue
    accent: deep orange
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
      
plugins:
  - search:
      separator: '[\s\-\.]+'
      prebuild_index: true

# Menu bar 
nav:
  - Tez : index.md
  - Getting started: GettingStarted.md

# Social Media link at footer
extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/abhi1thakur
  # - icon: fontawesome/brands/discord
  #   link: 
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/abhi1thakur
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/abhi1thakur
  - icon: fontawesome/solid/globe
    link: https://www.datamuni.com

# Extensions
markdown_extensions:
  - meta
  - admonition # alerts
  - pymdownx.details #  collapsible alerts
  - pymdownx.superfences # nest code and content inside alerts
  - attr_list # add HTML and CSS to Markdown elements
  - pymdownx.inlinehilite # inline code highlights
  - pymdownx.keys # show keystroke symbols
  - pymdownx.snippets # insert content from other files
  - pymdownx.tabbed # content tabs
  - footnotes
  - def_list
  - pymdownx.arithmatex: # mathjax
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - codehilite
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      toc_depth: 4